/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AllowIndexing": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Media": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PayloadSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Pdf": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RateLimits": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SiteUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TotpEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}